### ISSUE TITLE
Web Backend

### ISSUE THREAD

**Issue by sortedcord** [BVNCodeTech/codetech-web#27]
### Discussed in https://github.com/BVNCodeTech/codetech-web/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **sortedcord** November 17, 2021</sup>
The front-end isn't complete, but I was thinking of hooking it up with some sort of back-end. Preferable with django or flask as per what @Pancham1603 says ~Cuz PHP sucks anyways~ . The site is more or less fine without it, but I think this could make the work of maintaining and updating it a lot more easier....</div>

**Comment by Pancham1603** [comment]
can make placeholder text everywhere being fetched from a db. updating stuff will be easier then

**Comment by Pancham1603** [comment]
having a backend is not an issue but hosting is, i guess that was the primary reason to make a new static website

**Comment by sortedcord** [comment]
I found the best hosting service for this, and it's free https://www.pythonanywhere.com/ 

Its got reasonable CPU, disk limits which is more than enough. Basically its meant for hosting flask/django webapps

**Comment by Pancham1603** [comment]
I am in then, if we are playing around so much so let the `index.html` just have `{{ html|safe }}` and fetch all the html content from a database so that editing the website content gets lot more easier. Adding blog posts, projects etc. ez

**Comment by sortedcord** [comment]
That's one thing, but I like the front-end of the website being separated from the back-end/db. It is usually not such a good practice to do that, but if that makes things more easy then that's fine as well. Creating a back-end project for this repo then.

**Comment by Pancham1603** [comment]
we still need a hosting cuz pythonanywhere.com has a cpu limit of 100seconds/day and doesn't allow custom domains and there's a lot more, ig we'll have tk stick to the front-end

**Comment by sortedcord** [comment]
This will be a static site.
